// actionTypes.js

export const ADD_EVENT = 'ADD_EVENT';
export const ADD_SERVICE = 'ADD_SERVICE';
export const ADD_PACKAGE = 'ADD_PACKAGE';
export const VIEW_ALL_EVENTS = 'VIEW_ALL_EVENTS';
export const VIEW_ALL_SERVICES = 'VIEW_ALL_SERVICES';
export const VIEW_ALL_PACKAGES = 'VIEW_ALL_PACKAGES';
export const SEARCH_EVENT = 'SEARCH_EVENT';
export const SEARCH_SERVICE = 'SEARCH_SERVICE';
export const SEARCH_PACKAGE = 'SEARCH_PACKAGE';
export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_SERVICE = 'DELETE_SERVICE';
export const DELETE_PACKAGE = 'DELETE_PACKAGE';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
export const CHANGE_ADMIN_STATUS = 'CHANGE_ADMIN_STATUS';
export const FETCH_SERVICES_TYPE_WISE_SUCCESS = 'FETCH_SERVICES_TYPE_WISE_SUCCESS';
export const FETCH_SERVICES_TYPE_WISE_FAILURE = 'FETCH_SERVICES_TYPE_WISE_FAILURE';

